### ISSUE TITLE
Usernames with spaces

### ISSUE THREAD

**Issue by siyangqiu** [Mulliman/PanoCapture#1]
Hi there! Found your plugin from Reddit. I'm the guy who asked you where the Capture One plugin SDK docs were.

I found a bug: the plugin won't work for user accounts that have a space in the name. 
Will work:

> C:\Users\johndoe\

Won't work:

> C:\Users\john doe\

The issue occurs because when you pass in C:\Users\john doe as an argument for your new process, the space causes everything after the space to be a new argument rather than part of the path.

You need to update the lines to say:
`RunProcessToEnd("pto_gen.exe", $" -o \"{_outputProjectPath}\" {_inputFilesAsArguments}");`

Adding in quotes around the paths (and escaping the " with \ ).

**Comment by Mulliman** [comment]
Hey, thanks for raising this.

Attached is an updated package that should hopefully fix the issue.

Can you test this fixes your issue, and if so I'll update the release on the website.


[UnzipMeThenInstall.zip](https://github.com/Mulliman/PanoCapture/files/6096894/UnzipMeThenInstall.zip)

**Comment by Mulliman** [comment]
Also, I found I needed to restart C1 after installing for the generated files to automatically appear in the browser.

**Comment by siyangqiu** [comment]
"Create Panorama" is working. "Create Blended Stack" still isn't. That probably needs a similar update as tempStackedFile is also a path in the RunProcessToEnd process.

One more thing: the tip in the Preferences settings says "Plase click or tab" instead of "Please click or tab".

**Comment by Mulliman** [comment]
I wrapped the blended stack ones with quotes in the same way that I did for created panorama, so I was expecting that to work too.

Can you send over the most recent blended stack logs that are stored in C:\Users\{Username}\AppData\Roaming\PanoCapture

It would be good to know at which stage it breaks and hopefully it logs the exception.

Cheers

P.s. I've changed that typo.

**Comment by siyangqiu** [comment]
`Creating control points between C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02478.tif and C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02479.tif
Trying to find 8 corners... 
Number of good matches: 8, bad matches: 13
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 5, bad matches: 0
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 1, bad matches: 2
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 2, bad matches: 38
Number of good matches: 4, bad matches: 33
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 4, bad matches: 36
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 1, bad matches: 39
Number of good matches: 8, bad matches: 32
Number of good matches: 1, bad matches: 39
Creating control points between C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02479.tif and C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02480.tif
Trying to find 8 corners... 
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 20
Number of good matches: 3, bad matches: 1
Number of good matches: 8, bad matches: 12
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 0, bad matches: 2
Number of good matches: 0, bad matches: 33
Number of good matches: 8, bad matches: 32
Number of good matches: 1, bad matches: 39
Number of good matches: 0, bad matches: 40
Number of good matches: 8, bad matches: 30
Number of good matches: 7, bad matches: 33
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 30
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 4, bad matches: 36
Number of good matches: 8, bad matches: 32
Number of good matches: 8, bad matches: 32
Number of good matches: 6, bad matches: 34
Creating control points between C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02480.tif and C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02482.tif
Trying to find 8 corners... 
Number of good matches: 2, bad matches: 21
Number of good matches: 1, bad matches: 3
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 29
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 12
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Creating control points between C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02482.tif and C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\DSC02481.tif
Trying to find 8 corners... 
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 38
Number of good matches: 0, bad matches: 40
Number of good matches: 3, bad matches: 3
Number of good matches: 1, bad matches: 39
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Number of good matches: 0, bad matches: 40
Optimizing Variables
Strategy 1
Average (rms) distance between Controlpoints 
after 0 iteration(s):          54.9723809442167 units
Strategy 1
Average (rms) distance between Controlpoints 
after 1 iteration(s):          44.7736525468003 units
Strategy 1
Average (rms) distance between Controlpoints 
after 2 iteration(s):          31.7049553945868 units
Strategy 1
Average (rms) distance between Controlpoints 
after 3 iteration(s):           30.996672195255 units
Strategy 1
Average (rms) distance between Controlpoints 
after 4 iteration(s):          23.1125531395342 units
Strategy 1
Average (rms) distance between Controlpoints 
after 5 iteration(s):          22.2784796375642 units
Strategy 1
Average (rms) distance between Controlpoints 
after 6 iteration(s):          21.6791619009024 units
Strategy 1
Average (rms) distance between Controlpoints 
after 7 iteration(s):           21.450800706962 units

Optimizing Variables
Strategy 2
Average (rms) distance between Controlpoints 
after 0 iteration(s):          21.4508841483579 units
Strategy 2
Average (rms) distance between Controlpoints 
after 1 iteration(s):           21.088553419309 units
Strategy 2
Average (rms) distance between Controlpoints 
after 2 iteration(s):          20.9870458647231 units
Strategy 2
Average (rms) distance between Controlpoints 
after 3 iteration(s):          20.9845512719703 units
Strategy 2
Average (rms) distance between Controlpoints 
after 4 iteration(s):           20.982474324797 units
Strategy 2
Average (rms) distance between Controlpoints 
after 5 iteration(s):          20.9822537251446 units
Strategy 2
Average (rms) distance between Controlpoints 
after 6 iteration(s):           20.982213917013 units
Strategy 2
Average (rms) distance between Controlpoints 
after 7 iteration(s):          20.9821342165943 units
Strategy 2
Average (rms) distance between Controlpoints 
after 8 iteration(s):          20.9821182376503 units
Strategy 2
Average (rms) distance between Controlpoints 
after 9 iteration(s):          20.9820862596473 units
Strategy 2
Average (rms) distance between Controlpoints 
after 10 iteration(s):          20.9820222225983 units
Strategy 2
Average (rms) distance between Controlpoints 
after 11 iteration(s):          20.9820209393987 units

Ctrl points before pruning: 326, after: 10
EXCEPTION THROWN!
Could not find file 'C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\a.tif'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at PanoCapture.Process.BlendedStackBuilder.RunBuild(Boolean crop) in C:\Development\Photography\PanoCapture\PanoCapture\PanoCapture.Process\BlendedStackBuilder.cs:line 71
`

Hmmm... the path is correct, but somehow the output file isn't being produced. I didn't test this before submitting the issue originally as I assumed the quotes were the only issue.

Speaking of logs: Did you know that Console.Out.WriteLine() will write to Capture One's own logging system with logs in C:\Users\{Username}\Local\CaptureOne\Logs?

**Comment by Mulliman** [comment]
So does 'C:\Users\Siyang Qiu\AppData\Local\Temp\CaptureOneTemp1\679f1cd9-5538-47b8-905e-ae8012738150\a.tif' exists?

When I built it I was expecting a different file name, but enfuse always named it a.tif on my machine so I hardcoded that into the plugin. I'm wondering if your version of Hugin calls it something different.

**Comment by siyangqiu** [comment]
Ah figured it out. It didn't like the images I put in. It worked when I put in a different set of files.

**Comment by Mulliman** [comment]
Thanks for continuing to look into it and finding the issue.

**Comment by siyangqiu** [comment]
No problem! Thanks for making this plugin! 

Now you just need to update your website and GitHub with the new version.

**Comment by Mulliman** [comment]
Everything is now pushed.
